/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package com.eltherm.topcomponents;

import com.eltherm.services.RepaintService;
import com.eltherm.services.ToolsService;
import com.eltherm.services.UIbuilderService;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.eltherm.topcomponents//Eltherm_VisualBoard//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "Eltherm_VisualBoardTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "com.eltherm.topcomponents.Eltherm_VisualBoardTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_Eltherm_VisualBoardAction",
        preferredID = "Eltherm_VisualBoardTopComponent"
)
@Messages({
    "CTL_Eltherm_VisualBoardAction=Eltherm_VisualBoard",
    "CTL_Eltherm_VisualBoardTopComponent=Eltherm_VisualBoard Window",
    "HINT_Eltherm_VisualBoardTopComponent=This is a Eltherm_VisualBoard window"
})
public final class Eltherm_VisualBoardTopComponent extends TopComponent {

            
    private final UIbuilderService uibuilder;
    private final RepaintService repaintService;
    private final ToolsService toolsService;
    
    public Eltherm_VisualBoardTopComponent() {
        initComponents();
        setName(Bundle.CTL_Eltherm_VisualBoardTopComponent());
        setToolTipText(Bundle.HINT_Eltherm_VisualBoardTopComponent());
        
        
        //build navigator panel
        JPanel navigator_panel = new JPanel();
        
        //Build main panel for editing elements
        JPanel visual_board_panel = new JPanel();
        
        repaintService = new RepaintService(navigator_panel, visual_board_panel);
        
        toolsService = new ToolsService(visual_board_panel);
        
        //build symbole_panel via uibuilder
        uibuilder = new UIbuilderService(repaintService,toolsService);
        uibuilder.build_navigator_panel(navigator_panel);
        uibuilder.build_visual_board_panel(visual_board_panel);
        
        //set BorderLayout as main layout
        setLayout(new BorderLayout(10,10));
        
        //Set empty Border
        setBorder(new EmptyBorder(5,5,5,5));
        add(navigator_panel,BorderLayout.WEST);
        add(visual_board_panel,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
